name: Build MMOItemsCollection

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        working-directory: ./MMOItemsCollection
        run: mvn -B clean package

      - name: Check build output
        run: ls -lah ./MMOItemsCollection/target/

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: MMOItemsCollection
          path: ./MMOItemsCollection/target/*.jar
          if-no-files-found: error
